# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=128)),
                ('comp_email', models.EmailField(max_length=264, unique=True)),
                ('comp_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
